Style.create(style: "Hollowbody Electric")
Style.create(style: "Semi-Hollowbody Electric")
Style.create(style: "Solidbody Electric")
Style.create(style: "Flattop Steel String Acoustic")
Style.create(style: "Nylon String Acoustic")
Style.create(style: "Artchtop Acoustic")

Maker.create(name: "Gibson")
Maker.create(name: "Fender")
Maker.create(name: "D'Angelico")
Maker.create(name: "Martin")
Maker.create(name: "Ibanez")
Maker.create(name: "Danelectro")
Maker.create(name: "Epiphone")
Maker.create(name: "Roland")
Maker.create(name: "Guild")
Maker.create(name: "Gretch")